float:
  any:
  - base_args: ['@metric']
    constructor: BaseANN
    disabled: true
    docker_tag: ann-benchmarks-base
    module: ann_benchmarks.algorithms.base
    name: base
    run_groups:
      base:
        args: [[32, 64, 128, 256, 512, 1024, 2048, 4096]]